#!/bin/bash

echo "Running golangci-lint..."


if ! command -v golangci-lint &> /dev/null
then
  echo "golangci-lint could not be found. Please install it."
  exit 1
fi


golangci-lint run

if [ $? -ne 0 ]; then
  echo "Linter failed. Please fix the issues before committing."
  exit 1
fi
